### ISSUE TITLE
[0.0.1] SAG Mill from EnderIO crashes game when used with Block Analyzer + Remote Interface

### ISSUE THREAD

**Issue by SPMoo66** [dmillerw/RemoteIO#83]
Tried an SAG Mill on top of a Block Analyzer, game crashed. On another note, Alloy Smelter did not crash the game, but appeared as an invisible block with the Remote Interface.

http://pastebin.com/Y688CYNg

Cooking for Blockheads' Oven crashed the game as well upon attempting to break it, in the same exact way.
http://pastebin.com/zinxc3Gz

**Comment by dmillerw** [comment]
Should be fixed in 0.0.2. Let me know if otherwise

**Comment by SPMoo66** [comment]
Unfortunately no, it still crashes the game. Appears invisible, then crashes when I looked at it.

http://pastebin.com/z1v4XJB3

**Comment by dmillerw** [comment]
Pretty sure I know the issue then, will be fixed in next release, hopefully tonight!

**Comment by dmillerw** [comment]
I've fixed the crashing, but the invisible blocks will still require some tinkering
